import { useEffect, useState } from 'react'
import { motion } from 'framer-motion'
import { recommendationsApi } from '../api/recommendations'
import { useApp } from '../context/AppContext'
import { RefreshCw, Loader2, TrendingUp, Package, Users, Megaphone, BarChart } from 'lucide-react'

const CAT_ICONS = { revenue: TrendingUp, inventory: Package, retention: Users, marketing: Megaphone, product: BarChart }
const SEV_STYLES = {
  high: 'severity-high',
  medium: 'severity-medium',
  low: 'severity-low',
}

export default function RecommendationsPage() {
  const { notify } = useApp()
  const [recs, setRecs] = useState([])
  const [loading, setLoading] = useState(true)
  const [refreshing, setRefreshing] = useState(false)

  const load = (refresh = false) => {
    if (refresh) setRefreshing(true)
    else setLoading(true)
    recommendationsApi.get(refresh)
      .then(res => setRecs(res.data.recommendations || []))
      .catch(() => notify('Failed to load recommendations', 'error'))
      .finally(() => { setLoading(false); setRefreshing(false) })
  }

  useEffect(() => { load() }, [])

  return (
    <div className="p-7 space-y-5 animate-fade-in">
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-white font-semibold">AI Insights & Recommendations</h2>
          <p className="text-white/30 text-sm mt-0.5">Generated by AI analysis of your business data</p>
        </div>
        <button onClick={() => load(true)} disabled={refreshing}
          className="btn-secondary flex items-center gap-2 text-xs">
          {refreshing ? <Loader2 size={14} className="animate-spin" /> : <RefreshCw size={14} />}
          Refresh
        </button>
      </div>

      {loading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {[1,2,3,4].map(i => (
            <div key={i} className="glass-card p-5 animate-pulse h-36" />
          ))}
        </div>
      ) : (
        <motion.div initial="hidden" animate="show"
          variants={{ hidden: {}, show: { transition: { staggerChildren: 0.07 } } }}
          className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {recs.map((rec, i) => {
            const Icon = CAT_ICONS[rec.category] || TrendingUp
            return (
              <motion.div key={i} variants={{ hidden: { opacity: 0, y: 14 }, show: { opacity: 1, y: 0 } }}
                className="glass-card p-5 hover:border-white/[0.14] transition-all">
                <div className="flex items-start gap-4">
                  <div className="w-10 h-10 rounded-xl bg-brand-500/15 flex items-center justify-center flex-shrink-0">
                    <Icon size={18} className="text-brand-400" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-2 flex-wrap">
                      <span className="text-white font-semibold text-sm">{rec.title}</span>
                      <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full border ${SEV_STYLES[rec.severity] || SEV_STYLES.low}`}>
                        {rec.severity}
                      </span>
                    </div>
                    <p className="text-white/50 text-xs leading-relaxed mb-3">{rec.text}</p>
                    <div className="flex items-center justify-between">
                      {rec.metric && <span className="text-xs text-brand-400 font-medium">{rec.metric}</span>}
                      {rec.action && (
                        <button className="text-xs text-brand-400 hover:text-white border border-brand-500/30 hover:border-brand-500 px-2.5 py-1 rounded-lg transition-all">
                          {rec.action} →
                        </button>
                      )}
                    </div>
                  </div>
                </div>
              </motion.div>
            )
          })}
        </motion.div>
      )}
    </div>
  )
}
